---

- name: Config tasks
  tags:
    - sudo_config
    - sudo
  become: true
  block:
    - name: Manage dropin config directory
      ansible.builtin.file:
        path: "{{ sudo_dropin_config_dir }}"
        owner: root
        group: root
        mode: 0750

    - name: Manage dropin configuration
      when:
        - sudo_dropin_config_options is defined and sudo_dropin_config_options 
        - (item.state is defined and item.state == 'present') or
          item.state is undefined
      ansible.builtin.template:
        src: sudoers.dropin.j2
        dest: "{{ sudo_dropin_config_dir }}/{{ item.file }}"
        mode: 0440
        owner: root
        group: root
        validate: 'visudo -cf %s'
      with_items: "{{ sudo_dropin_config_options }}"

    - name: Remove dropin configration
      when:
        - sudo_dropin_config_options is defined and sudo_dropin_config_options
        - item.state is defined and item.state == 'absent'
      ansible.builtin.file:
        path: "{{ sudo_dropin_config_dir }}/{{ item.file }}"
        state: absent
      with_items: "{{ sudo_dropin_config_options }}"
