---

- name: Install sudo tasks
  tags:
    - sudo_install
    - sudo
  become: true
  block:

  - name: Install packages
    when: ansible_os_family == 'Debian'
    ansible.builtin.apt:
      name: ["{{ item }}"]
      update_cache: true
      state: "{{ sudo_package_ensure }}"
    with_items: "{{ sudo_package_name }}"

  - name: Install packages
    when: ansible_os_family == 'RedHat'
    ansible.builtin.yum:
      name: ["{{ item }}"]
      state: "{{ sudo_package_ensure }}"
    with_items: "{{ sudo_package_name }}"
